//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/repos/AssetRipper.Translation.LlvmIR/AssetRipper.Translation.LlvmIR/DemangledNames.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AssetRipper.Translation.LlvmIR {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DemangledNamesParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDemangledNamesVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction([NotNull] DemangledNamesParser.FunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionPrefix([NotNull] DemangledNamesParser.FunctionPrefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSuffix([NotNull] DemangledNamesParser.FunctionSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionReturnType([NotNull] DemangledNamesParser.FunctionReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionDeclaringScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaringScope([NotNull] DemangledNamesParser.FunctionDeclaringScopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameter([NotNull] DemangledNamesParser.FunctionParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionParameters([NotNull] DemangledNamesParser.FunctionParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateParameter([NotNull] DemangledNamesParser.TemplateParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate([NotNull] DemangledNamesParser.TemplateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.templateNotNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateNotNull([NotNull] DemangledNamesParser.TemplateNotNullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionName([NotNull] DemangledNamesParser.FunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] DemangledNamesParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.functionIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionIdentifier([NotNull] DemangledNamesParser.FunctionIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] DemangledNamesParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.typeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeIdentifier([NotNull] DemangledNamesParser.TypeIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.qualifiedTypeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedTypeIdentifier([NotNull] DemangledNamesParser.QualifiedTypeIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessModifier([NotNull] DemangledNamesParser.AccessModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.vcSpecificModifer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVcSpecificModifer([NotNull] DemangledNamesParser.VcSpecificModiferContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumericType([NotNull] DemangledNamesParser.NumericTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerType([NotNull] DemangledNamesParser.IntegerTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator([NotNull] DemangledNamesParser.OperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.operatorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorName([NotNull] DemangledNamesParser.OperatorNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticOperator([NotNull] DemangledNamesParser.ArithmeticOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] DemangledNamesParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOperator([NotNull] DemangledNamesParser.LogicalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DemangledNamesParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftOperator([NotNull] DemangledNamesParser.ShiftOperatorContext context);
}
} // namespace AssetRipper.Translation.LlvmIR
