//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/repos/AssetRipper.Translation.LlvmIR/AssetRipper.Translation.LlvmIR/DemangledNames.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AssetRipper.Translation.LlvmIR {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DemangledNamesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IDemangledNamesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] DemangledNamesParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] DemangledNamesParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionPrefix([NotNull] DemangledNamesParser.FunctionPrefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionPrefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionPrefix([NotNull] DemangledNamesParser.FunctionPrefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSuffix([NotNull] DemangledNamesParser.FunctionSuffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSuffix([NotNull] DemangledNamesParser.FunctionSuffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionReturnType([NotNull] DemangledNamesParser.FunctionReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionReturnType([NotNull] DemangledNamesParser.FunctionReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionDeclaringScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDeclaringScope([NotNull] DemangledNamesParser.FunctionDeclaringScopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionDeclaringScope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDeclaringScope([NotNull] DemangledNamesParser.FunctionDeclaringScopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionParameter([NotNull] DemangledNamesParser.FunctionParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionParameter([NotNull] DemangledNamesParser.FunctionParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionParameters([NotNull] DemangledNamesParser.FunctionParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionParameters([NotNull] DemangledNamesParser.FunctionParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateParameter([NotNull] DemangledNamesParser.TemplateParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateParameter([NotNull] DemangledNamesParser.TemplateParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplate([NotNull] DemangledNamesParser.TemplateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.template"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplate([NotNull] DemangledNamesParser.TemplateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.templateNotNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateNotNull([NotNull] DemangledNamesParser.TemplateNotNullContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.templateNotNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateNotNull([NotNull] DemangledNamesParser.TemplateNotNullContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionName([NotNull] DemangledNamesParser.FunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionName([NotNull] DemangledNamesParser.FunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] DemangledNamesParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] DemangledNamesParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionIdentifier([NotNull] DemangledNamesParser.FunctionIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionIdentifier([NotNull] DemangledNamesParser.FunctionIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] DemangledNamesParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] DemangledNamesParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.typeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdentifier([NotNull] DemangledNamesParser.TypeIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.typeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdentifier([NotNull] DemangledNamesParser.TypeIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.qualifiedTypeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedTypeIdentifier([NotNull] DemangledNamesParser.QualifiedTypeIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.qualifiedTypeIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedTypeIdentifier([NotNull] DemangledNamesParser.QualifiedTypeIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessModifier([NotNull] DemangledNamesParser.AccessModifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.accessModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessModifier([NotNull] DemangledNamesParser.AccessModifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.vcSpecificModifer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVcSpecificModifer([NotNull] DemangledNamesParser.VcSpecificModiferContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.vcSpecificModifer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVcSpecificModifer([NotNull] DemangledNamesParser.VcSpecificModiferContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumericType([NotNull] DemangledNamesParser.NumericTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.numericType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumericType([NotNull] DemangledNamesParser.NumericTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerType([NotNull] DemangledNamesParser.IntegerTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.integerType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerType([NotNull] DemangledNamesParser.IntegerTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperator([NotNull] DemangledNamesParser.OperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperator([NotNull] DemangledNamesParser.OperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.operatorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorName([NotNull] DemangledNamesParser.OperatorNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.operatorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorName([NotNull] DemangledNamesParser.OperatorNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticOperator([NotNull] DemangledNamesParser.ArithmeticOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticOperator([NotNull] DemangledNamesParser.ArithmeticOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalOperator([NotNull] DemangledNamesParser.RelationalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalOperator([NotNull] DemangledNamesParser.RelationalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOperator([NotNull] DemangledNamesParser.LogicalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.logicalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOperator([NotNull] DemangledNamesParser.LogicalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftOperator([NotNull] DemangledNamesParser.ShiftOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftOperator([NotNull] DemangledNamesParser.ShiftOperatorContext context);
}
} // namespace AssetRipper.Translation.LlvmIR
