//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/repos/AssetRipper.Translation.LlvmIR/AssetRipper.Translation.LlvmIR/DemangledNames.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AssetRipper.Translation.LlvmIR {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class DemangledNamesParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, EscapedString=2, AccessModifier=3, CallingConvention=4, NewOrDelete=5, 
		TypeKeyword=6, Bool=7, Char=8, Const=9, DeclTypeAuto=10, Float=11, Int=12, 
		Int64=13, Long=14, Operator=15, Short=16, Signed=17, Static=18, Unsigned=19, 
		Virtual=20, Void=21, LeftParen=22, RightParen=23, Less=24, Greater=25, 
		Equals=26, Plus=27, Minus=28, Star=29, Slash=30, Modulo=31, And=32, Pipe=33, 
		Caret=34, Tilde=35, Exclamation=36, Colon=37, Comma=38, BackTick=39, SingleQuote=40, 
		DoubleQuote=41, LeftBrace=42, RightBrace=43, LeftBracket=44, RightBracket=45, 
		Identifier=46, Number=47, Whitespace=48, Newline=49;
	public const int
		RULE_function = 0, RULE_functionPrefix = 1, RULE_functionSuffix = 2, RULE_functionReturnType = 3, 
		RULE_functionDeclaringScope = 4, RULE_functionParameter = 5, RULE_functionParameters = 6, 
		RULE_templateParameter = 7, RULE_template = 8, RULE_templateNotNull = 9, 
		RULE_functionName = 10, RULE_identifier = 11, RULE_functionIdentifier = 12, 
		RULE_type = 13, RULE_typeIdentifier = 14, RULE_qualifiedTypeIdentifier = 15, 
		RULE_numericType = 16, RULE_integerType = 17, RULE_operator = 18, RULE_operatorName = 19, 
		RULE_arithmeticOperator = 20, RULE_relationalOperator = 21, RULE_logicalOperator = 22, 
		RULE_shiftOperator = 23;
	public static readonly string[] ruleNames = {
		"function", "functionPrefix", "functionSuffix", "functionReturnType", 
		"functionDeclaringScope", "functionParameter", "functionParameters", "templateParameter", 
		"template", "templateNotNull", "functionName", "identifier", "functionIdentifier", 
		"type", "typeIdentifier", "qualifiedTypeIdentifier", "numericType", "integerType", 
		"operator", "operatorName", "arithmeticOperator", "relationalOperator", 
		"logicalOperator", "shiftOperator"
	};

	private static readonly string[] _LiteralNames = {
		null, "'_Static'", null, null, null, null, null, "'bool'", "'char'", "'const'", 
		"'decltype(auto)'", "'float'", "'int'", "'__int64'", "'long'", "'operator'", 
		"'short'", "'signed'", "'static'", "'unsigned'", "'virtual'", "'void'", 
		"'('", "')'", "'<'", "'>'", "'='", "'+'", "'-'", "'*'", "'/'", "'%'", 
		"'&'", "'|'", "'^'", "'~'", "'!'", "':'", "','", "'`'", "'''", "'\"'", 
		"'{'", "'}'", "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "EscapedString", "AccessModifier", "CallingConvention", "NewOrDelete", 
		"TypeKeyword", "Bool", "Char", "Const", "DeclTypeAuto", "Float", "Int", 
		"Int64", "Long", "Operator", "Short", "Signed", "Static", "Unsigned", 
		"Virtual", "Void", "LeftParen", "RightParen", "Less", "Greater", "Equals", 
		"Plus", "Minus", "Star", "Slash", "Modulo", "And", "Pipe", "Caret", "Tilde", 
		"Exclamation", "Colon", "Comma", "BackTick", "SingleQuote", "DoubleQuote", 
		"LeftBrace", "RightBrace", "LeftBracket", "RightBracket", "Identifier", 
		"Number", "Whitespace", "Newline"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "DemangledNames.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static DemangledNamesParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public DemangledNamesParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public DemangledNamesParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FunctionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionPrefixContext functionPrefix() {
			return GetRuleContext<FunctionPrefixContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionReturnTypeContext functionReturnType() {
			return GetRuleContext<FunctionReturnTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CallingConvention() { return GetToken(DemangledNamesParser.CallingConvention, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDeclaringScopeContext functionDeclaringScope() {
			return GetRuleContext<FunctionDeclaringScopeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionNameContext functionName() {
			return GetRuleContext<FunctionNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParen() { return GetToken(DemangledNamesParser.LeftParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionParametersContext functionParameters() {
			return GetRuleContext<FunctionParametersContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParen() { return GetToken(DemangledNamesParser.RightParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionSuffixContext functionSuffix() {
			return GetRuleContext<FunctionSuffixContext>(0);
		}
		public FunctionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionContext function() {
		FunctionContext _localctx = new FunctionContext(Context, State);
		EnterRule(_localctx, 0, RULE_function);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 48;
			functionPrefix();
			State = 49;
			functionReturnType();
			State = 50;
			Match(CallingConvention);
			State = 51;
			functionDeclaringScope();
			State = 52;
			functionName();
			State = 53;
			Match(LeftParen);
			State = 54;
			functionParameters();
			State = 55;
			Match(RightParen);
			State = 56;
			functionSuffix();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionPrefixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AccessModifier() { return GetToken(DemangledNamesParser.AccessModifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon() { return GetToken(DemangledNamesParser.Colon, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Virtual() { return GetToken(DemangledNamesParser.Virtual, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Static() { return GetToken(DemangledNamesParser.Static, 0); }
		public FunctionPrefixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionPrefix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionPrefix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionPrefix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionPrefix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionPrefixContext functionPrefix() {
		FunctionPrefixContext _localctx = new FunctionPrefixContext(Context, State);
		EnterRule(_localctx, 2, RULE_functionPrefix);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
			case 1:
				{
				State = 58;
				Match(AccessModifier);
				State = 59;
				Match(Colon);
				}
				break;
			}
			State = 63;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				{
				State = 62;
				_la = TokenStream.LA(1);
				if ( !(_la==Static || _la==Virtual) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionSuffixContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Const() { return GetToken(DemangledNamesParser.Const, 0); }
		public FunctionSuffixContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionSuffix; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionSuffix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionSuffix(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionSuffix(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionSuffixContext functionSuffix() {
		FunctionSuffixContext _localctx = new FunctionSuffixContext(Context, State);
		EnterRule(_localctx, 4, RULE_functionSuffix);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Const) {
				{
				State = 65;
				Match(Const);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionReturnTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public FunctionReturnTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionReturnType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionReturnType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionReturnType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionReturnType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionReturnTypeContext functionReturnType() {
		FunctionReturnTypeContext _localctx = new FunctionReturnTypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_functionReturnType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				{
				State = 68;
				type(0);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclaringScopeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedTypeIdentifierContext qualifiedTypeIdentifier() {
			return GetRuleContext<QualifiedTypeIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Colon() { return GetTokens(DemangledNamesParser.Colon); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon(int i) {
			return GetToken(DemangledNamesParser.Colon, i);
		}
		public FunctionDeclaringScopeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDeclaringScope; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionDeclaringScope(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionDeclaringScope(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDeclaringScope(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDeclaringScopeContext functionDeclaringScope() {
		FunctionDeclaringScopeContext _localctx = new FunctionDeclaringScopeContext(Context, State);
		EnterRule(_localctx, 8, RULE_functionDeclaringScope);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				State = 71;
				qualifiedTypeIdentifier(0);
				State = 72;
				Match(Colon);
				State = 73;
				Match(Colon);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionParameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Const() { return GetToken(DemangledNamesParser.Const, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(DemangledNamesParser.And, 0); }
		public FunctionParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionParameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionParameter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionParameter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionParameterContext functionParameter() {
		FunctionParameterContext _localctx = new FunctionParameterContext(Context, State);
		EnterRule(_localctx, 10, RULE_functionParameter);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 77;
			type(0);
			State = 79;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Const) {
				{
				State = 78;
				Match(Const);
				}
			}

			State = 82;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==And) {
				{
				State = 81;
				Match(And);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionParametersContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionParameterContext[] functionParameter() {
			return GetRuleContexts<FunctionParameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionParameterContext functionParameter(int i) {
			return GetRuleContext<FunctionParameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(DemangledNamesParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(DemangledNamesParser.Comma, i);
		}
		public FunctionParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionParameters; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionParameters(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionParameters(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionParametersContext functionParameters() {
		FunctionParametersContext _localctx = new FunctionParametersContext(Context, State);
		EnterRule(_localctx, 12, RULE_functionParameters);
		int _la;
		try {
			State = 93;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case EscapedString:
			case AccessModifier:
			case CallingConvention:
			case NewOrDelete:
			case TypeKeyword:
			case Bool:
			case Char:
			case Const:
			case DeclTypeAuto:
			case Float:
			case Int:
			case Int64:
			case Long:
			case Operator:
			case Short:
			case Signed:
			case Static:
			case Unsigned:
			case Virtual:
			case Void:
			case Less:
			case Identifier:
				EnterOuterAlt(_localctx, 1);
				{
				State = 84;
				functionParameter();
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Comma) {
					{
					{
					State = 85;
					Match(Comma);
					State = 86;
					functionParameter();
					}
					}
					State = 91;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case RightParen:
				EnterOuterAlt(_localctx, 2);
				{
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TemplateParameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Const() { return GetToken(DemangledNamesParser.Const, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(DemangledNamesParser.And, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(DemangledNamesParser.Number, 0); }
		public TemplateParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_templateParameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterTemplateParameter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitTemplateParameter(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplateParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TemplateParameterContext templateParameter() {
		TemplateParameterContext _localctx = new TemplateParameterContext(Context, State);
		EnterRule(_localctx, 14, RULE_templateParameter);
		int _la;
		try {
			State = 103;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case EscapedString:
			case AccessModifier:
			case CallingConvention:
			case NewOrDelete:
			case TypeKeyword:
			case Bool:
			case Char:
			case Const:
			case DeclTypeAuto:
			case Float:
			case Int:
			case Int64:
			case Long:
			case Operator:
			case Short:
			case Signed:
			case Static:
			case Unsigned:
			case Virtual:
			case Void:
			case Less:
			case Identifier:
				EnterOuterAlt(_localctx, 1);
				{
				State = 95;
				type(0);
				State = 97;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Const) {
					{
					State = 96;
					Match(Const);
					}
				}

				State = 100;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==And) {
					{
					State = 99;
					Match(And);
					}
				}

				}
				break;
			case Number:
				EnterOuterAlt(_localctx, 2);
				{
				State = 102;
				Match(Number);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TemplateContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less() { return GetToken(DemangledNamesParser.Less, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TemplateParameterContext[] templateParameter() {
			return GetRuleContexts<TemplateParameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TemplateParameterContext templateParameter(int i) {
			return GetRuleContext<TemplateParameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(DemangledNamesParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(DemangledNamesParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(DemangledNamesParser.Comma, i);
		}
		public TemplateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_template; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterTemplate(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitTemplate(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TemplateContext template() {
		TemplateContext _localctx = new TemplateContext(Context, State);
		EnterRule(_localctx, 16, RULE_template);
		int _la;
		try {
			State = 119;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 105;
				Match(Less);
				State = 106;
				templateParameter();
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Comma) {
					{
					{
					State = 107;
					Match(Comma);
					State = 108;
					templateParameter();
					}
					}
					State = 113;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 114;
				Match(Greater);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 116;
				Match(Less);
				State = 117;
				Match(Greater);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TemplateNotNullContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less() { return GetToken(DemangledNamesParser.Less, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TemplateParameterContext[] templateParameter() {
			return GetRuleContexts<TemplateParameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TemplateParameterContext templateParameter(int i) {
			return GetRuleContext<TemplateParameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(DemangledNamesParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Comma() { return GetTokens(DemangledNamesParser.Comma); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Comma(int i) {
			return GetToken(DemangledNamesParser.Comma, i);
		}
		public TemplateNotNullContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_templateNotNull; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterTemplateNotNull(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitTemplateNotNull(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplateNotNull(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TemplateNotNullContext templateNotNull() {
		TemplateNotNullContext _localctx = new TemplateNotNullContext(Context, State);
		EnterRule(_localctx, 18, RULE_templateNotNull);
		int _la;
		try {
			State = 134;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,15,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 121;
				Match(Less);
				State = 122;
				templateParameter();
				State = 127;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Comma) {
					{
					{
					State = 123;
					Match(Comma);
					State = 124;
					templateParameter();
					}
					}
					State = 129;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 130;
				Match(Greater);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 132;
				Match(Less);
				State = 133;
				Match(Greater);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public FunctionIdentifierContext functionIdentifier() {
			return GetRuleContext<FunctionIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TemplateContext template() {
			return GetRuleContext<TemplateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftBracket() { return GetToken(DemangledNamesParser.LeftBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightBracket() { return GetToken(DemangledNamesParser.RightBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TemplateNotNullContext[] templateNotNull() {
			return GetRuleContexts<TemplateNotNullContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TemplateNotNullContext templateNotNull(int i) {
			return GetRuleContext<TemplateNotNullContext>(i);
		}
		public FunctionNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionNameContext functionName() {
		FunctionNameContext _localctx = new FunctionNameContext(Context, State);
		EnterRule(_localctx, 20, RULE_functionName);
		try {
			State = 148;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 136;
				functionIdentifier();
				State = 137;
				template();
				{
				State = 138;
				Match(LeftBracket);
				State = 139;
				Match(RightBracket);
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 141;
				functionIdentifier();
				State = 142;
				templateNotNull();
				State = 143;
				templateNotNull();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 145;
				functionIdentifier();
				State = 146;
				template();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Identifier() { return GetToken(DemangledNamesParser.Identifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EscapedString() { return GetToken(DemangledNamesParser.EscapedString, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AccessModifier() { return GetToken(DemangledNamesParser.AccessModifier, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CallingConvention() { return GetToken(DemangledNamesParser.CallingConvention, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NewOrDelete() { return GetToken(DemangledNamesParser.NewOrDelete, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TypeKeyword() { return GetToken(DemangledNamesParser.TypeKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Bool() { return GetToken(DemangledNamesParser.Bool, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Char() { return GetToken(DemangledNamesParser.Char, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Const() { return GetToken(DemangledNamesParser.Const, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Float() { return GetToken(DemangledNamesParser.Float, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Int() { return GetToken(DemangledNamesParser.Int, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Int64() { return GetToken(DemangledNamesParser.Int64, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Long() { return GetToken(DemangledNamesParser.Long, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Operator() { return GetToken(DemangledNamesParser.Operator, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Short() { return GetToken(DemangledNamesParser.Short, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Signed() { return GetToken(DemangledNamesParser.Signed, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Static() { return GetToken(DemangledNamesParser.Static, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Unsigned() { return GetToken(DemangledNamesParser.Unsigned, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Virtual() { return GetToken(DemangledNamesParser.Virtual, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Void() { return GetToken(DemangledNamesParser.Void, 0); }
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 22, RULE_identifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 150;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 70368748370940L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionIdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public OperatorContext @operator() {
			return GetRuleContext<OperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tilde() { return GetToken(DemangledNamesParser.Tilde, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SingleQuote() { return GetTokens(DemangledNamesParser.SingleQuote); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SingleQuote(int i) {
			return GetToken(DemangledNamesParser.SingleQuote, i);
		}
		public FunctionIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionIdentifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterFunctionIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitFunctionIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionIdentifierContext functionIdentifier() {
		FunctionIdentifierContext _localctx = new FunctionIdentifierContext(Context, State);
		EnterRule(_localctx, 24, RULE_functionIdentifier);
		int _la;
		try {
			State = 164;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,19,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 152;
				@operator();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 154;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Tilde) {
					{
					State = 153;
					Match(Tilde);
					}
				}

				State = 157;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 156;
					identifier();
					}
					}
					State = 159;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 70368748370940L) != 0) );
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 161;
				Match(T__0);
				State = 162;
				Match(SingleQuote);
				State = 163;
				Match(SingleQuote);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedTypeIdentifierContext qualifiedTypeIdentifier() {
			return GetRuleContext<QualifiedTypeIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TypeKeyword() { return GetToken(DemangledNamesParser.TypeKeyword, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Const() { return GetToken(DemangledNamesParser.Const, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Star() { return GetTokens(DemangledNamesParser.Star); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Star(int i) {
			return GetToken(DemangledNamesParser.Star, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] And() { return GetTokens(DemangledNamesParser.And); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And(int i) {
			return GetToken(DemangledNamesParser.And, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LeftParen() { return GetTokens(DemangledNamesParser.LeftParen); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParen(int i) {
			return GetToken(DemangledNamesParser.LeftParen, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RightParen() { return GetTokens(DemangledNamesParser.RightParen); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParen(int i) {
			return GetToken(DemangledNamesParser.RightParen, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftBracket() { return GetToken(DemangledNamesParser.LeftBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number() { return GetToken(DemangledNamesParser.Number, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightBracket() { return GetToken(DemangledNamesParser.RightBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CallingConvention() { return GetToken(DemangledNamesParser.CallingConvention, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public FunctionParametersContext functionParameters() {
			return GetRuleContext<FunctionParametersContext>(0);
		}
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		return type(0);
	}

	private TypeContext type(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		TypeContext _localctx = new TypeContext(Context, _parentState);
		TypeContext _prevctx = _localctx;
		int _startState = 26;
		EnterRecursionRule(_localctx, 26, RULE_type, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 168;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,20,Context) ) {
			case 1:
				{
				State = 167;
				Match(TypeKeyword);
				}
				break;
			}
			State = 170;
			qualifiedTypeIdentifier(0);
			State = 172;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				{
				State = 171;
				Match(Const);
				}
				break;
			}
			State = 177;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 174;
					_la = TokenStream.LA(1);
					if ( !(_la==Star || _la==And) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					}
					} 
				}
				State = 179;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,22,Context);
			}
			}
			Context.Stop = TokenStream.LT(-1);
			State = 210;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 208;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
					case 1:
						{
						_localctx = new TypeContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_type);
						State = 180;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 181;
						Match(LeftParen);
						State = 182;
						Match(Star);
						State = 183;
						Match(Const);
						State = 184;
						Match(RightParen);
						State = 185;
						Match(LeftBracket);
						State = 186;
						Match(Number);
						State = 187;
						Match(RightBracket);
						}
						break;
					case 2:
						{
						_localctx = new TypeContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_type);
						State = 188;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 189;
						Match(LeftParen);
						State = 190;
						Match(And);
						State = 191;
						Match(RightParen);
						State = 192;
						Match(LeftBracket);
						State = 193;
						Match(Number);
						State = 194;
						Match(RightBracket);
						}
						break;
					case 3:
						{
						_localctx = new TypeContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_type);
						State = 195;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 196;
						Match(LeftBracket);
						State = 197;
						Match(Number);
						State = 198;
						Match(RightBracket);
						}
						break;
					case 4:
						{
						_localctx = new TypeContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_type);
						State = 199;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 200;
						Match(LeftParen);
						State = 201;
						Match(CallingConvention);
						State = 202;
						Match(Star);
						State = 203;
						Match(RightParen);
						State = 204;
						Match(LeftParen);
						State = 205;
						functionParameters();
						State = 206;
						Match(RightParen);
						}
						break;
					}
					} 
				}
				State = 212;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TypeIdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Void() { return GetToken(DemangledNamesParser.Void, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DeclTypeAuto() { return GetToken(DemangledNamesParser.DeclTypeAuto, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumericTypeContext numericType() {
			return GetRuleContext<NumericTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TemplateContext template() {
			return GetRuleContext<TemplateContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less() { return GetToken(DemangledNamesParser.Less, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(DemangledNamesParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Minus() { return GetTokens(DemangledNamesParser.Minus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus(int i) {
			return GetToken(DemangledNamesParser.Minus, i);
		}
		public TypeIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeIdentifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterTypeIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitTypeIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeIdentifierContext typeIdentifier() {
		TypeIdentifierContext _localctx = new TypeIdentifierContext(Context, State);
		EnterRule(_localctx, 28, RULE_typeIdentifier);
		int _la;
		try {
			int _alt;
			State = 242;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,28,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 213;
				Match(Void);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 214;
				Match(DeclTypeAuto);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 215;
				numericType();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 217;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 216;
						identifier();
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 219;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,25,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				State = 221;
				template();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 223;
				Match(Less);
				State = 225;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 224;
					identifier();
					}
					}
					State = 227;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 70368748370940L) != 0) );
				State = 229;
				Match(Greater);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 231;
				Match(Less);
				State = 232;
				identifier();
				State = 237;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==Minus) {
					{
					{
					State = 233;
					Match(Minus);
					State = 234;
					identifier();
					}
					}
					State = 239;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 240;
				Match(Greater);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiedTypeIdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeIdentifierContext typeIdentifier() {
			return GetRuleContext<TypeIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedTypeIdentifierContext qualifiedTypeIdentifier() {
			return GetRuleContext<QualifiedTypeIdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Colon() { return GetTokens(DemangledNamesParser.Colon); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Colon(int i) {
			return GetToken(DemangledNamesParser.Colon, i);
		}
		public QualifiedTypeIdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiedTypeIdentifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterQualifiedTypeIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitQualifiedTypeIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualifiedTypeIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QualifiedTypeIdentifierContext qualifiedTypeIdentifier() {
		return qualifiedTypeIdentifier(0);
	}

	private QualifiedTypeIdentifierContext qualifiedTypeIdentifier(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		QualifiedTypeIdentifierContext _localctx = new QualifiedTypeIdentifierContext(Context, _parentState);
		QualifiedTypeIdentifierContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_qualifiedTypeIdentifier, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 245;
			typeIdentifier();
			}
			Context.Stop = TokenStream.LT(-1);
			State = 253;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,29,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new QualifiedTypeIdentifierContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_qualifiedTypeIdentifier);
					State = 247;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 248;
					Match(Colon);
					State = 249;
					Match(Colon);
					State = 250;
					typeIdentifier();
					}
					} 
				}
				State = 255;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,29,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumericTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Bool() { return GetToken(DemangledNamesParser.Bool, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Float() { return GetToken(DemangledNamesParser.Float, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Unsigned() { return GetToken(DemangledNamesParser.Unsigned, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IntegerTypeContext integerType() {
			return GetRuleContext<IntegerTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Signed() { return GetToken(DemangledNamesParser.Signed, 0); }
		public NumericTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numericType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterNumericType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitNumericType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumericType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumericTypeContext numericType() {
		NumericTypeContext _localctx = new NumericTypeContext(Context, State);
		EnterRule(_localctx, 32, RULE_numericType);
		try {
			State = 263;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Bool:
				EnterOuterAlt(_localctx, 1);
				{
				State = 256;
				Match(Bool);
				}
				break;
			case Float:
				EnterOuterAlt(_localctx, 2);
				{
				State = 257;
				Match(Float);
				}
				break;
			case Unsigned:
				EnterOuterAlt(_localctx, 3);
				{
				State = 258;
				Match(Unsigned);
				State = 259;
				integerType();
				}
				break;
			case Signed:
				EnterOuterAlt(_localctx, 4);
				{
				State = 260;
				Match(Signed);
				State = 261;
				integerType();
				}
				break;
			case Char:
			case Int:
			case Int64:
			case Long:
			case Short:
				EnterOuterAlt(_localctx, 5);
				{
				State = 262;
				integerType();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IntegerTypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Char() { return GetToken(DemangledNamesParser.Char, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Short() { return GetToken(DemangledNamesParser.Short, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Int() { return GetToken(DemangledNamesParser.Int, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Int64() { return GetToken(DemangledNamesParser.Int64, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Long() { return GetTokens(DemangledNamesParser.Long); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Long(int i) {
			return GetToken(DemangledNamesParser.Long, i);
		}
		public IntegerTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_integerType; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterIntegerType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitIntegerType(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntegerType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IntegerTypeContext integerType() {
		IntegerTypeContext _localctx = new IntegerTypeContext(Context, State);
		EnterRule(_localctx, 34, RULE_integerType);
		try {
			State = 272;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 265;
				Match(Char);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 266;
				Match(Short);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 267;
				Match(Int);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 268;
				Match(Int64);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 269;
				Match(Long);
				State = 270;
				Match(Long);
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 271;
				Match(Long);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Operator() { return GetToken(DemangledNamesParser.Operator, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public OperatorNameContext operatorName() {
			return GetRuleContext<OperatorNameContext>(0);
		}
		public OperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperatorContext @operator() {
		OperatorContext _localctx = new OperatorContext(Context, State);
		EnterRule(_localctx, 36, RULE_operator);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 274;
			Match(Operator);
			State = 275;
			operatorName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperatorNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NewOrDelete() { return GetToken(DemangledNamesParser.NewOrDelete, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftBracket() { return GetToken(DemangledNamesParser.LeftBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightBracket() { return GetToken(DemangledNamesParser.RightBracket, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NumericTypeContext numericType() {
			return GetRuleContext<NumericTypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ShiftOperatorContext shiftOperator() {
			return GetRuleContext<ShiftOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Equals() { return GetToken(DemangledNamesParser.Equals, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArithmeticOperatorContext arithmeticOperator() {
			return GetRuleContext<ArithmeticOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LogicalOperatorContext logicalOperator() {
			return GetRuleContext<LogicalOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public RelationalOperatorContext relationalOperator() {
			return GetRuleContext<RelationalOperatorContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Exclamation() { return GetToken(DemangledNamesParser.Exclamation, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Plus() { return GetTokens(DemangledNamesParser.Plus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus(int i) {
			return GetToken(DemangledNamesParser.Plus, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Minus() { return GetTokens(DemangledNamesParser.Minus); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus(int i) {
			return GetToken(DemangledNamesParser.Minus, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LeftParen() { return GetToken(DemangledNamesParser.LeftParen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RightParen() { return GetToken(DemangledNamesParser.RightParen, 0); }
		public OperatorNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operatorName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterOperatorName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitOperatorName(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperatorName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperatorNameContext operatorName() {
		OperatorNameContext _localctx = new OperatorNameContext(Context, State);
		EnterRule(_localctx, 38, RULE_operatorName);
		int _la;
		try {
			State = 305;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,35,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 277;
				Match(NewOrDelete);
				State = 278;
				Match(LeftBracket);
				State = 279;
				Match(RightBracket);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 280;
				Match(NewOrDelete);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 281;
				numericType();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 282;
				shiftOperator();
				State = 284;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Equals) {
					{
					State = 283;
					Match(Equals);
					}
				}

				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 286;
				arithmeticOperator();
				State = 288;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Equals) {
					{
					State = 287;
					Match(Equals);
					}
				}

				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 290;
				logicalOperator();
				State = 292;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Equals) {
					{
					State = 291;
					Match(Equals);
					}
				}

				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 294;
				relationalOperator();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 295;
				Match(Exclamation);
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 296;
				Match(Equals);
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 297;
				Match(Plus);
				State = 298;
				Match(Plus);
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 299;
				Match(Minus);
				State = 300;
				Match(Minus);
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 301;
				Match(LeftBracket);
				State = 302;
				Match(RightBracket);
				}
				break;
			case 13:
				EnterOuterAlt(_localctx, 13);
				{
				State = 303;
				Match(LeftParen);
				State = 304;
				Match(RightParen);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArithmeticOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Plus() { return GetToken(DemangledNamesParser.Plus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Minus() { return GetToken(DemangledNamesParser.Minus, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Star() { return GetToken(DemangledNamesParser.Star, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Slash() { return GetToken(DemangledNamesParser.Slash, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Modulo() { return GetToken(DemangledNamesParser.Modulo, 0); }
		public ArithmeticOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arithmeticOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterArithmeticOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitArithmeticOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArithmeticOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArithmeticOperatorContext arithmeticOperator() {
		ArithmeticOperatorContext _localctx = new ArithmeticOperatorContext(Context, State);
		EnterRule(_localctx, 40, RULE_arithmeticOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 307;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 4160749568L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RelationalOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less() { return GetToken(DemangledNamesParser.Less, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Equals() { return GetTokens(DemangledNamesParser.Equals); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Equals(int i) {
			return GetToken(DemangledNamesParser.Equals, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater() { return GetToken(DemangledNamesParser.Greater, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Exclamation() { return GetToken(DemangledNamesParser.Exclamation, 0); }
		public RelationalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationalOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterRelationalOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitRelationalOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalOperatorContext relationalOperator() {
		RelationalOperatorContext _localctx = new RelationalOperatorContext(Context, State);
		EnterRule(_localctx, 42, RULE_relationalOperator);
		int _la;
		try {
			State = 321;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Less:
				EnterOuterAlt(_localctx, 1);
				{
				State = 309;
				Match(Less);
				State = 311;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Equals) {
					{
					State = 310;
					Match(Equals);
					}
				}

				}
				break;
			case Greater:
				EnterOuterAlt(_localctx, 2);
				{
				State = 313;
				Match(Greater);
				State = 315;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==Equals) {
					{
					State = 314;
					Match(Equals);
					}
				}

				}
				break;
			case Equals:
				EnterOuterAlt(_localctx, 3);
				{
				State = 317;
				Match(Equals);
				State = 318;
				Match(Equals);
				}
				break;
			case Exclamation:
				EnterOuterAlt(_localctx, 4);
				{
				State = 319;
				Match(Exclamation);
				State = 320;
				Match(Equals);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LogicalOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode And() { return GetToken(DemangledNamesParser.And, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Pipe() { return GetToken(DemangledNamesParser.Pipe, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Caret() { return GetToken(DemangledNamesParser.Caret, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Tilde() { return GetToken(DemangledNamesParser.Tilde, 0); }
		public LogicalOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterLogicalOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitLogicalOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalOperatorContext logicalOperator() {
		LogicalOperatorContext _localctx = new LogicalOperatorContext(Context, State);
		EnterRule(_localctx, 44, RULE_logicalOperator);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 323;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 64424509440L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ShiftOperatorContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Less() { return GetTokens(DemangledNamesParser.Less); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Less(int i) {
			return GetToken(DemangledNamesParser.Less, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Greater() { return GetTokens(DemangledNamesParser.Greater); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Greater(int i) {
			return GetToken(DemangledNamesParser.Greater, i);
		}
		public ShiftOperatorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_shiftOperator; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.EnterShiftOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IDemangledNamesListener typedListener = listener as IDemangledNamesListener;
			if (typedListener != null) typedListener.ExitShiftOperator(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IDemangledNamesVisitor<TResult> typedVisitor = visitor as IDemangledNamesVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitShiftOperator(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ShiftOperatorContext shiftOperator() {
		ShiftOperatorContext _localctx = new ShiftOperatorContext(Context, State);
		EnterRule(_localctx, 46, RULE_shiftOperator);
		try {
			State = 329;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case Less:
				EnterOuterAlt(_localctx, 1);
				{
				State = 325;
				Match(Less);
				State = 326;
				Match(Less);
				}
				break;
			case Greater:
				EnterOuterAlt(_localctx, 2);
				{
				State = 327;
				Match(Greater);
				State = 328;
				Match(Greater);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 13: return type_sempred((TypeContext)_localctx, predIndex);
		case 15: return qualifiedTypeIdentifier_sempred((QualifiedTypeIdentifierContext)_localctx, predIndex);
		}
		return true;
	}
	private bool type_sempred(TypeContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}
	private bool qualifiedTypeIdentifier_sempred(QualifiedTypeIdentifierContext _localctx, int predIndex) {
		switch (predIndex) {
		case 4: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,49,332,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,3,
		1,61,8,1,1,1,3,1,64,8,1,1,2,3,2,67,8,2,1,3,3,3,70,8,3,1,4,1,4,1,4,1,4,
		3,4,76,8,4,1,5,1,5,3,5,80,8,5,1,5,3,5,83,8,5,1,6,1,6,1,6,5,6,88,8,6,10,
		6,12,6,91,9,6,1,6,3,6,94,8,6,1,7,1,7,3,7,98,8,7,1,7,3,7,101,8,7,1,7,3,
		7,104,8,7,1,8,1,8,1,8,1,8,5,8,110,8,8,10,8,12,8,113,9,8,1,8,1,8,1,8,1,
		8,1,8,3,8,120,8,8,1,9,1,9,1,9,1,9,5,9,126,8,9,10,9,12,9,129,9,9,1,9,1,
		9,1,9,1,9,3,9,135,8,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,
		1,10,1,10,3,10,149,8,10,1,11,1,11,1,12,1,12,3,12,155,8,12,1,12,4,12,158,
		8,12,11,12,12,12,159,1,12,1,12,1,12,3,12,165,8,12,1,13,1,13,3,13,169,8,
		13,1,13,1,13,3,13,173,8,13,1,13,5,13,176,8,13,10,13,12,13,179,9,13,1,13,
		1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,
		1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,5,13,
		209,8,13,10,13,12,13,212,9,13,1,14,1,14,1,14,1,14,4,14,218,8,14,11,14,
		12,14,219,1,14,1,14,1,14,1,14,4,14,226,8,14,11,14,12,14,227,1,14,1,14,
		1,14,1,14,1,14,1,14,5,14,236,8,14,10,14,12,14,239,9,14,1,14,1,14,3,14,
		243,8,14,1,15,1,15,1,15,1,15,1,15,1,15,1,15,5,15,252,8,15,10,15,12,15,
		255,9,15,1,16,1,16,1,16,1,16,1,16,1,16,1,16,3,16,264,8,16,1,17,1,17,1,
		17,1,17,1,17,1,17,1,17,3,17,273,8,17,1,18,1,18,1,18,1,19,1,19,1,19,1,19,
		1,19,1,19,1,19,3,19,285,8,19,1,19,1,19,3,19,289,8,19,1,19,1,19,3,19,293,
		8,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,19,3,19,306,8,
		19,1,20,1,20,1,21,1,21,3,21,312,8,21,1,21,1,21,3,21,316,8,21,1,21,1,21,
		1,21,1,21,3,21,322,8,21,1,22,1,22,1,23,1,23,1,23,1,23,3,23,330,8,23,1,
		23,0,2,26,30,24,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,
		40,42,44,46,0,5,2,0,18,18,20,20,3,0,2,9,11,21,46,46,2,0,29,29,32,32,1,
		0,27,31,1,0,32,35,376,0,48,1,0,0,0,2,60,1,0,0,0,4,66,1,0,0,0,6,69,1,0,
		0,0,8,75,1,0,0,0,10,77,1,0,0,0,12,93,1,0,0,0,14,103,1,0,0,0,16,119,1,0,
		0,0,18,134,1,0,0,0,20,148,1,0,0,0,22,150,1,0,0,0,24,164,1,0,0,0,26,166,
		1,0,0,0,28,242,1,0,0,0,30,244,1,0,0,0,32,263,1,0,0,0,34,272,1,0,0,0,36,
		274,1,0,0,0,38,305,1,0,0,0,40,307,1,0,0,0,42,321,1,0,0,0,44,323,1,0,0,
		0,46,329,1,0,0,0,48,49,3,2,1,0,49,50,3,6,3,0,50,51,5,4,0,0,51,52,3,8,4,
		0,52,53,3,20,10,0,53,54,5,22,0,0,54,55,3,12,6,0,55,56,5,23,0,0,56,57,3,
		4,2,0,57,1,1,0,0,0,58,59,5,3,0,0,59,61,5,37,0,0,60,58,1,0,0,0,60,61,1,
		0,0,0,61,63,1,0,0,0,62,64,7,0,0,0,63,62,1,0,0,0,63,64,1,0,0,0,64,3,1,0,
		0,0,65,67,5,9,0,0,66,65,1,0,0,0,66,67,1,0,0,0,67,5,1,0,0,0,68,70,3,26,
		13,0,69,68,1,0,0,0,69,70,1,0,0,0,70,7,1,0,0,0,71,72,3,30,15,0,72,73,5,
		37,0,0,73,74,5,37,0,0,74,76,1,0,0,0,75,71,1,0,0,0,75,76,1,0,0,0,76,9,1,
		0,0,0,77,79,3,26,13,0,78,80,5,9,0,0,79,78,1,0,0,0,79,80,1,0,0,0,80,82,
		1,0,0,0,81,83,5,32,0,0,82,81,1,0,0,0,82,83,1,0,0,0,83,11,1,0,0,0,84,89,
		3,10,5,0,85,86,5,38,0,0,86,88,3,10,5,0,87,85,1,0,0,0,88,91,1,0,0,0,89,
		87,1,0,0,0,89,90,1,0,0,0,90,94,1,0,0,0,91,89,1,0,0,0,92,94,1,0,0,0,93,
		84,1,0,0,0,93,92,1,0,0,0,94,13,1,0,0,0,95,97,3,26,13,0,96,98,5,9,0,0,97,
		96,1,0,0,0,97,98,1,0,0,0,98,100,1,0,0,0,99,101,5,32,0,0,100,99,1,0,0,0,
		100,101,1,0,0,0,101,104,1,0,0,0,102,104,5,47,0,0,103,95,1,0,0,0,103,102,
		1,0,0,0,104,15,1,0,0,0,105,106,5,24,0,0,106,111,3,14,7,0,107,108,5,38,
		0,0,108,110,3,14,7,0,109,107,1,0,0,0,110,113,1,0,0,0,111,109,1,0,0,0,111,
		112,1,0,0,0,112,114,1,0,0,0,113,111,1,0,0,0,114,115,5,25,0,0,115,120,1,
		0,0,0,116,117,5,24,0,0,117,120,5,25,0,0,118,120,1,0,0,0,119,105,1,0,0,
		0,119,116,1,0,0,0,119,118,1,0,0,0,120,17,1,0,0,0,121,122,5,24,0,0,122,
		127,3,14,7,0,123,124,5,38,0,0,124,126,3,14,7,0,125,123,1,0,0,0,126,129,
		1,0,0,0,127,125,1,0,0,0,127,128,1,0,0,0,128,130,1,0,0,0,129,127,1,0,0,
		0,130,131,5,25,0,0,131,135,1,0,0,0,132,133,5,24,0,0,133,135,5,25,0,0,134,
		121,1,0,0,0,134,132,1,0,0,0,135,19,1,0,0,0,136,137,3,24,12,0,137,138,3,
		16,8,0,138,139,5,44,0,0,139,140,5,45,0,0,140,149,1,0,0,0,141,142,3,24,
		12,0,142,143,3,18,9,0,143,144,3,18,9,0,144,149,1,0,0,0,145,146,3,24,12,
		0,146,147,3,16,8,0,147,149,1,0,0,0,148,136,1,0,0,0,148,141,1,0,0,0,148,
		145,1,0,0,0,149,21,1,0,0,0,150,151,7,1,0,0,151,23,1,0,0,0,152,165,3,36,
		18,0,153,155,5,35,0,0,154,153,1,0,0,0,154,155,1,0,0,0,155,157,1,0,0,0,
		156,158,3,22,11,0,157,156,1,0,0,0,158,159,1,0,0,0,159,157,1,0,0,0,159,
		160,1,0,0,0,160,165,1,0,0,0,161,162,5,1,0,0,162,163,5,40,0,0,163,165,5,
		40,0,0,164,152,1,0,0,0,164,154,1,0,0,0,164,161,1,0,0,0,165,25,1,0,0,0,
		166,168,6,13,-1,0,167,169,5,6,0,0,168,167,1,0,0,0,168,169,1,0,0,0,169,
		170,1,0,0,0,170,172,3,30,15,0,171,173,5,9,0,0,172,171,1,0,0,0,172,173,
		1,0,0,0,173,177,1,0,0,0,174,176,7,2,0,0,175,174,1,0,0,0,176,179,1,0,0,
		0,177,175,1,0,0,0,177,178,1,0,0,0,178,210,1,0,0,0,179,177,1,0,0,0,180,
		181,10,4,0,0,181,182,5,22,0,0,182,183,5,29,0,0,183,184,5,9,0,0,184,185,
		5,23,0,0,185,186,5,44,0,0,186,187,5,47,0,0,187,209,5,45,0,0,188,189,10,
		3,0,0,189,190,5,22,0,0,190,191,5,32,0,0,191,192,5,23,0,0,192,193,5,44,
		0,0,193,194,5,47,0,0,194,209,5,45,0,0,195,196,10,2,0,0,196,197,5,44,0,
		0,197,198,5,47,0,0,198,209,5,45,0,0,199,200,10,1,0,0,200,201,5,22,0,0,
		201,202,5,4,0,0,202,203,5,29,0,0,203,204,5,23,0,0,204,205,5,22,0,0,205,
		206,3,12,6,0,206,207,5,23,0,0,207,209,1,0,0,0,208,180,1,0,0,0,208,188,
		1,0,0,0,208,195,1,0,0,0,208,199,1,0,0,0,209,212,1,0,0,0,210,208,1,0,0,
		0,210,211,1,0,0,0,211,27,1,0,0,0,212,210,1,0,0,0,213,243,5,21,0,0,214,
		243,5,10,0,0,215,243,3,32,16,0,216,218,3,22,11,0,217,216,1,0,0,0,218,219,
		1,0,0,0,219,217,1,0,0,0,219,220,1,0,0,0,220,221,1,0,0,0,221,222,3,16,8,
		0,222,243,1,0,0,0,223,225,5,24,0,0,224,226,3,22,11,0,225,224,1,0,0,0,226,
		227,1,0,0,0,227,225,1,0,0,0,227,228,1,0,0,0,228,229,1,0,0,0,229,230,5,
		25,0,0,230,243,1,0,0,0,231,232,5,24,0,0,232,237,3,22,11,0,233,234,5,28,
		0,0,234,236,3,22,11,0,235,233,1,0,0,0,236,239,1,0,0,0,237,235,1,0,0,0,
		237,238,1,0,0,0,238,240,1,0,0,0,239,237,1,0,0,0,240,241,5,25,0,0,241,243,
		1,0,0,0,242,213,1,0,0,0,242,214,1,0,0,0,242,215,1,0,0,0,242,217,1,0,0,
		0,242,223,1,0,0,0,242,231,1,0,0,0,243,29,1,0,0,0,244,245,6,15,-1,0,245,
		246,3,28,14,0,246,253,1,0,0,0,247,248,10,2,0,0,248,249,5,37,0,0,249,250,
		5,37,0,0,250,252,3,28,14,0,251,247,1,0,0,0,252,255,1,0,0,0,253,251,1,0,
		0,0,253,254,1,0,0,0,254,31,1,0,0,0,255,253,1,0,0,0,256,264,5,7,0,0,257,
		264,5,11,0,0,258,259,5,19,0,0,259,264,3,34,17,0,260,261,5,17,0,0,261,264,
		3,34,17,0,262,264,3,34,17,0,263,256,1,0,0,0,263,257,1,0,0,0,263,258,1,
		0,0,0,263,260,1,0,0,0,263,262,1,0,0,0,264,33,1,0,0,0,265,273,5,8,0,0,266,
		273,5,16,0,0,267,273,5,12,0,0,268,273,5,13,0,0,269,270,5,14,0,0,270,273,
		5,14,0,0,271,273,5,14,0,0,272,265,1,0,0,0,272,266,1,0,0,0,272,267,1,0,
		0,0,272,268,1,0,0,0,272,269,1,0,0,0,272,271,1,0,0,0,273,35,1,0,0,0,274,
		275,5,15,0,0,275,276,3,38,19,0,276,37,1,0,0,0,277,278,5,5,0,0,278,279,
		5,44,0,0,279,306,5,45,0,0,280,306,5,5,0,0,281,306,3,32,16,0,282,284,3,
		46,23,0,283,285,5,26,0,0,284,283,1,0,0,0,284,285,1,0,0,0,285,306,1,0,0,
		0,286,288,3,40,20,0,287,289,5,26,0,0,288,287,1,0,0,0,288,289,1,0,0,0,289,
		306,1,0,0,0,290,292,3,44,22,0,291,293,5,26,0,0,292,291,1,0,0,0,292,293,
		1,0,0,0,293,306,1,0,0,0,294,306,3,42,21,0,295,306,5,36,0,0,296,306,5,26,
		0,0,297,298,5,27,0,0,298,306,5,27,0,0,299,300,5,28,0,0,300,306,5,28,0,
		0,301,302,5,44,0,0,302,306,5,45,0,0,303,304,5,22,0,0,304,306,5,23,0,0,
		305,277,1,0,0,0,305,280,1,0,0,0,305,281,1,0,0,0,305,282,1,0,0,0,305,286,
		1,0,0,0,305,290,1,0,0,0,305,294,1,0,0,0,305,295,1,0,0,0,305,296,1,0,0,
		0,305,297,1,0,0,0,305,299,1,0,0,0,305,301,1,0,0,0,305,303,1,0,0,0,306,
		39,1,0,0,0,307,308,7,3,0,0,308,41,1,0,0,0,309,311,5,24,0,0,310,312,5,26,
		0,0,311,310,1,0,0,0,311,312,1,0,0,0,312,322,1,0,0,0,313,315,5,25,0,0,314,
		316,5,26,0,0,315,314,1,0,0,0,315,316,1,0,0,0,316,322,1,0,0,0,317,318,5,
		26,0,0,318,322,5,26,0,0,319,320,5,36,0,0,320,322,5,26,0,0,321,309,1,0,
		0,0,321,313,1,0,0,0,321,317,1,0,0,0,321,319,1,0,0,0,322,43,1,0,0,0,323,
		324,7,4,0,0,324,45,1,0,0,0,325,326,5,24,0,0,326,330,5,24,0,0,327,328,5,
		25,0,0,328,330,5,25,0,0,329,325,1,0,0,0,329,327,1,0,0,0,330,47,1,0,0,0,
		40,60,63,66,69,75,79,82,89,93,97,100,103,111,119,127,134,148,154,159,164,
		168,172,177,208,210,219,227,237,242,253,263,272,284,288,292,305,311,315,
		321,329
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace AssetRipper.Translation.LlvmIR
