//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from e:/repos/AssetRipper.Translation.LlvmIR/AssetRipper.Translation.LlvmIR/DemangledNames.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace AssetRipper.Translation.LlvmIR {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDemangledNamesListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class DemangledNamesBaseListener : IDemangledNamesListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction([NotNull] DemangledNamesParser.FunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction([NotNull] DemangledNamesParser.FunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionPrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionPrefix([NotNull] DemangledNamesParser.FunctionPrefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionPrefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionPrefix([NotNull] DemangledNamesParser.FunctionPrefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSuffix([NotNull] DemangledNamesParser.FunctionSuffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionSuffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSuffix([NotNull] DemangledNamesParser.FunctionSuffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionReturnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionReturnType([NotNull] DemangledNamesParser.FunctionReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionReturnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionReturnType([NotNull] DemangledNamesParser.FunctionReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionDeclaringScope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaringScope([NotNull] DemangledNamesParser.FunctionDeclaringScopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionDeclaringScope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaringScope([NotNull] DemangledNamesParser.FunctionDeclaringScopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionParameter([NotNull] DemangledNamesParser.FunctionParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionParameter([NotNull] DemangledNamesParser.FunctionParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionParameters([NotNull] DemangledNamesParser.FunctionParametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionParameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionParameters([NotNull] DemangledNamesParser.FunctionParametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.templateParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateParameter([NotNull] DemangledNamesParser.TemplateParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.templateParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateParameter([NotNull] DemangledNamesParser.TemplateParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplate([NotNull] DemangledNamesParser.TemplateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.template"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplate([NotNull] DemangledNamesParser.TemplateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.templateNotNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateNotNull([NotNull] DemangledNamesParser.TemplateNotNullContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.templateNotNull"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateNotNull([NotNull] DemangledNamesParser.TemplateNotNullContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionName([NotNull] DemangledNamesParser.FunctionNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionName([NotNull] DemangledNamesParser.FunctionNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] DemangledNamesParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] DemangledNamesParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.functionIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionIdentifier([NotNull] DemangledNamesParser.FunctionIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.functionIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionIdentifier([NotNull] DemangledNamesParser.FunctionIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] DemangledNamesParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] DemangledNamesParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.typeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeIdentifier([NotNull] DemangledNamesParser.TypeIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.typeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeIdentifier([NotNull] DemangledNamesParser.TypeIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.qualifiedTypeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedTypeIdentifier([NotNull] DemangledNamesParser.QualifiedTypeIdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.qualifiedTypeIdentifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedTypeIdentifier([NotNull] DemangledNamesParser.QualifiedTypeIdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccessModifier([NotNull] DemangledNamesParser.AccessModifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.accessModifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccessModifier([NotNull] DemangledNamesParser.AccessModifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.vcSpecificModifer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVcSpecificModifer([NotNull] DemangledNamesParser.VcSpecificModiferContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.vcSpecificModifer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVcSpecificModifer([NotNull] DemangledNamesParser.VcSpecificModiferContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.numericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumericType([NotNull] DemangledNamesParser.NumericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.numericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumericType([NotNull] DemangledNamesParser.NumericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerType([NotNull] DemangledNamesParser.IntegerTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.integerType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerType([NotNull] DemangledNamesParser.IntegerTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperator([NotNull] DemangledNamesParser.OperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperator([NotNull] DemangledNamesParser.OperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemangledNamesParser.operatorName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperatorName([NotNull] DemangledNamesParser.OperatorNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemangledNamesParser.operatorName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperatorName([NotNull] DemangledNamesParser.OperatorNameContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace AssetRipper.Translation.LlvmIR
